In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
path = r"../rawdata/noaa-weather-downtown-sf.csv"

conv = {
        'DATE' : lambda x: dt.datetime.strptime(str(x),"%Y%m%d").date(),
    }

rawdf = pd.read_csv(path,converters = conv)



print rawdf.shape
print rawdf.dtypes
rawdf.tail(5)

(4836, 41)
STATION                   object
STATION_NAME              object
ELEVATION                float64
LATITUDE                 float64
LONGITUDE                float64
DATE                      object
PRCP                       int64
Measurement Flag          object
Quality Flag              object
Source Flag               object
Time of Observation        int64
SNWD                       int64
Measurement Flag.1        object
Quality Flag.1            object
Source Flag.1             object
Time of Observation.1      int64
SNOW                       int64
Measurement Flag.2        object
Quality Flag.2            object
Source Flag.2             object
Time of Observation.2      int64
TMAX                       int64
Measurement Flag.3        object
Quality Flag.3            object
Source Flag.3             object
Time of Observation.3      int64
TMIN                       int64
Measurement Flag.4        object
Quality Flag.4            object
Source Flag.4             object
Time of Observation.4      int64
TOBS                       int64
Measurement Flag.5        object
Quality Flag.5            object
Source Flag.5             object
Time of Observation.5      int64
WT11                       int64
Measurement Flag.6        object
Quality Flag.6            object
Source Flag.6             object
Time of Observation.6      int64
dtype: object

,STATION,STATION_NAME,ELEVATION,LATITUDE,LONGITUDE,DATE,PRCP,Measurement Flag,Quality Flag,Source Flag,...,TOBS,Measurement Flag.5,Quality Flag.5,Source Flag.5,Time of Observation.5,WT11,Measurement Flag.6,Quality Flag.6,Source Flag.6,Time of Observation.6
4831,GHCND:USW00023272,SAN FRANCISCO DOWNTOWN CA US,45.7,37.7705,-122.4269,2016-03-24,0,,,W,...,-9999,,,,9999,-9999,,,,9999
4832,GHCND:USW00023272,SAN FRANCISCO DOWNTOWN CA US,45.7,37.7705,-122.4269,2016-03-25,0,,,W,...,-9999,,,,9999,-9999,,,,9999
4833,GHCND:USW00023272,SAN FRANCISCO DOWNTOWN CA US,45.7,37.7705,-122.4269,2016-03-26,0,,,W,...,-9999,,,,9999,-9999,,,,9999
4834,GHCND:USW00023272,SAN FRANCISCO DOWNTOWN CA US,45.7,37.7705,-122.4269,2016-03-27,0,,,W,...,-9999,,,,9999,-9999,,,,9999
4835,GHCND:USW00023272,SAN FRANCISCO DOWNTOWN CA US,45.7,37.7705,-122.4269,2016-03-28,0,,,W,...,-9999,,,,9999,-9999,,,,9999

In [3]:
dropcols = ['STATION','STATION_NAME','ELEVATION', 'LATITUDE', 'LONGITUDE','Time of Observation',
            'SNOW', 'Measurement Flag.2', 'Quality Flag.2', 'Source Flag.2',
            'SNWD', 'Measurement Flag.1', 'Quality Flag.1', 'Source Flag.1',
            'TOBS', 'Measurement Flag.5', 'Quality Flag.5', 'Source Flag.5',
            'WT11', 'Measurement Flag.6', 'Quality Flag.6', 'Source Flag.6',
           'Time of Observation.1','Time of Observation.2','Time of Observation.3',
            'Time of Observation.4','Time of Observation.5','Time of Observation.6']
df = rawdf.drop(dropcols,axis=1)
df[df < -1000] = np.nan
df.TMAX = df.TMAX.astype(float)/10.
df.TMIN = df.TMIN.astype(float)/10.
df.tail(200)

,DATE,PRCP,Measurement Flag,Quality Flag,Source Flag,TMAX,Measurement Flag.3,Quality Flag.3,Source Flag.3,TMIN,Measurement Flag.4,Quality Flag.4,Source Flag.4
4636,NaN,0,NaN,NaN,NaN,20.6,NaN,NaN,NaN,12.8,NaN,NaN,NaN
4637,NaN,0,NaN,NaN,NaN,21.7,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4638,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,15.0,NaN,NaN,NaN
4639,NaN,0,NaN,NaN,NaN,19.4,NaN,NaN,NaN,15.0,NaN,NaN,NaN
4640,NaN,3,NaN,NaN,NaN,17.8,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4641,NaN,8,NaN,NaN,NaN,20.6,NaN,NaN,NaN,14.4,NaN,NaN,NaN
4642,NaN,0,NaN,NaN,NaN,19.4,NaN,NaN,NaN,15.0,NaN,NaN,NaN
4643,NaN,0,NaN,NaN,NaN,23.3,NaN,NaN,NaN,14.4,NaN,NaN,NaN
4644,NaN,0,NaN,NaN,NaN,29.4,NaN,NaN,NaN,14.4,NaN,NaN,NaN
4645,NaN,0,NaN,NaN,NaN,33.9,NaN,NaN,NaN,17.2,NaN,NaN,NaN
4646,NaN,0,NaN,NaN,NaN,31.7,NaN,NaN,NaN,16.1,NaN,NaN,NaN
4647,NaN,0,NaN,NaN,NaN,16.7,NaN,NaN,NaN,13.9,NaN,NaN,NaN
4648,NaN,0,NaN,NaN,NaN,20.6,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4649,NaN,0,NaN,NaN,NaN,32.2,NaN,NaN,NaN,15.6,NaN,NaN,NaN
4650,NaN,0,NaN,NaN,NaN,21.1,NaN,NaN,NaN,14.4,NaN,NaN,NaN
4651,NaN,0,NaN,NaN,NaN,18.3,NaN,NaN,NaN,13.9,NaN,NaN,NaN
4652,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4653,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,12.8,NaN,NaN,NaN
4654,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,14.4,NaN,NaN,NaN
4655,NaN,13,NaN,NaN,NaN,19.4,NaN,NaN,NaN,14.4,NaN,NaN,NaN
4656,NaN,0,NaN,NaN,NaN,22.2,NaN,NaN,NaN,15.0,NaN,NaN,NaN
4657,NaN,0,NaN,NaN,NaN,23.3,NaN,NaN,NaN,13.9,NaN,NaN,NaN
4658,NaN,0,NaN,NaN,NaN,20.6,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4659,NaN,0,NaN,NaN,NaN,22.2,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4660,NaN,0,NaN,NaN,NaN,22.8,NaN,NaN,NaN,15.0,NaN,NaN,NaN
4661,NaN,0,NaN,NaN,NaN,21.7,NaN,NaN,NaN,15.6,NaN,NaN,NaN
4662,NaN,0,NaN,NaN,NaN,22.2,NaN,NaN,NaN,15.0,NaN,NaN,NaN
4663,NaN,0,NaN,NaN,NaN,25.0,NaN,NaN,NaN,15.0,NaN,NaN,NaN
4664,NaN,0,NaN,NaN,NaN,23.3,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4665,NaN,0,NaN,NaN,NaN,22.2,NaN,NaN,NaN,15.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4806,NaN,0,NaN,NaN,NaN,18.3,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4807,NaN,0,NaN,NaN,NaN,21.7,NaN,NaN,NaN,11.1,NaN,NaN,NaN
4808,NaN,0,NaN,NaN,NaN,20.6,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4809,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4810,NaN,20,NaN,NaN,NaN,16.7,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4811,NaN,97,NaN,NaN,NaN,17.2,NaN,NaN,NaN,13.9,NaN,NaN,NaN
4812,NaN,328,NaN,NaN,NaN,17.2,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4813,NaN,114,NaN,NaN,NaN,15.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4814,NaN,135,NaN,NaN,NaN,13.9,NaN,NaN,NaN,8.9,NaN,NaN,NaN
4815,NaN,0,NaN,NaN,NaN,13.3,NaN,NaN,NaN,8.3,NaN,NaN,NaN
4816,NaN,38,NaN,NaN,NaN,17.2,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4817,NaN,279,NaN,NaN,NaN,16.1,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4818,NaN,135,NaN,NaN,NaN,13.9,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4819,NaN,290,NaN,NaN,NaN,14.4,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4820,NaN,150,NaN,NaN,NaN,14.4,NaN,NaN,NaN,12.8,NaN,NaN,NaN
4821,NaN,0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4822,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,8.9,NaN,NaN,NaN
4823,NaN,0,NaN,NaN,NaN,21.1,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4824,NaN,0,NaN,NaN,NaN,23.9,NaN,NaN,NaN,11.7,NaN,NaN,NaN
4825,NaN,0,NaN,NaN,NaN,16.1,NaN,NaN,NaN,11.1,NaN,NaN,NaN
4826,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4827,NaN,25,NaN,NaN,NaN,17.8,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4828,NaN,104,NaN,NaN,NaN,16.1,NaN,NaN,NaN,9.4,NaN,NaN,NaN
4829,NaN,20,NaN,NaN,NaN,15.0,NaN,NaN,NaN,9.4,NaN,NaN,NaN
4830,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4831,NaN,0,NaN,NaN,NaN,17.2,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4832,NaN,0,NaN,NaN,NaN,18.3,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4833,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4834,NaN,0,NaN,NaN,NaN,15.6,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4835,NaN,0,NaN,NaN,NaN,14.4,NaN,NaN,NaN,8.9,NaN,NaN,NaN

In [4]:
df['PRCP'].describe()

count    4836.000000
mean       15.068238
std        54.591978
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       864.000000
Name: PRCP, dtype: float64

In [5]:
df['Quality Flag.3'].value_counts()

Series([], Name: Quality Flag.3, dtype: int64)

In [6]:
df[(df['Quality Flag.3'] != " ")]

,DATE,PRCP,Measurement Flag,Quality Flag,Source Flag,TMAX,Measurement Flag.3,Quality Flag.3,Source Flag.3,TMIN,Measurement Flag.4,Quality Flag.4,Source Flag.4
0,NaN,0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,7.8,NaN,NaN,NaN
1,NaN,0,NaN,NaN,NaN,13.9,NaN,NaN,NaN,8.9,NaN,NaN,NaN
2,NaN,0,NaN,NaN,NaN,17.2,NaN,NaN,NaN,8.3,NaN,NaN,NaN
3,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4,NaN,0,NaN,NaN,NaN,20.6,NaN,NaN,NaN,9.4,NaN,NaN,NaN
5,NaN,0,NaN,NaN,NaN,20.6,NaN,NaN,NaN,11.1,NaN,NaN,NaN
6,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,8.3,NaN,NaN,NaN
7,NaN,0,NaN,NaN,NaN,17.2,NaN,NaN,NaN,7.2,NaN,NaN,NaN
8,NaN,251,NaN,NaN,NaN,13.3,NaN,NaN,NaN,10.0,NaN,NaN,NaN
9,NaN,33,NaN,NaN,NaN,16.1,NaN,NaN,NaN,11.7,NaN,NaN,NaN
10,NaN,0,NaN,NaN,NaN,15.6,NaN,NaN,NaN,11.7,NaN,NaN,NaN
11,NaN,15,NaN,NaN,NaN,16.1,NaN,NaN,NaN,12.2,NaN,NaN,NaN
12,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,12.2,NaN,NaN,NaN
13,NaN,0,NaN,NaN,NaN,16.7,NaN,NaN,NaN,10.6,NaN,NaN,NaN
14,NaN,0,NaN,NaN,NaN,19.4,NaN,NaN,NaN,10.0,NaN,NaN,NaN
15,NaN,0,NaN,NaN,NaN,19.4,NaN,NaN,NaN,9.4,NaN,NaN,NaN
16,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,8.9,NaN,NaN,NaN
17,NaN,0,NaN,NaN,NaN,16.1,NaN,NaN,NaN,7.2,NaN,NaN,NaN
18,NaN,0,NaN,NaN,NaN,11.1,NaN,NaN,NaN,6.7,NaN,NaN,NaN
19,NaN,5,NaN,NaN,NaN,10.6,NaN,NaN,NaN,6.7,NaN,NaN,NaN
20,NaN,86,NaN,NaN,NaN,14.4,NaN,NaN,NaN,9.4,NaN,NaN,NaN
21,NaN,43,NaN,NaN,NaN,16.1,NaN,NaN,NaN,10.6,NaN,NaN,NaN
22,NaN,10,NaN,NaN,NaN,16.1,NaN,NaN,NaN,12.8,NaN,NaN,NaN
23,NaN,0,NaN,NaN,NaN,17.2,NaN,NaN,NaN,12.2,NaN,NaN,NaN
24,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,11.7,NaN,NaN,NaN
25,NaN,0,NaN,NaN,NaN,16.7,NaN,NaN,NaN,12.8,NaN,NaN,NaN
26,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
27,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
28,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,9.4,NaN,NaN,NaN
29,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,10.6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4806,NaN,0,NaN,NaN,NaN,18.3,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4807,NaN,0,NaN,NaN,NaN,21.7,NaN,NaN,NaN,11.1,NaN,NaN,NaN
4808,NaN,0,NaN,NaN,NaN,20.6,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4809,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4810,NaN,20,NaN,NaN,NaN,16.7,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4811,NaN,97,NaN,NaN,NaN,17.2,NaN,NaN,NaN,13.9,NaN,NaN,NaN
4812,NaN,328,NaN,NaN,NaN,17.2,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4813,NaN,114,NaN,NaN,NaN,15.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4814,NaN,135,NaN,NaN,NaN,13.9,NaN,NaN,NaN,8.9,NaN,NaN,NaN
4815,NaN,0,NaN,NaN,NaN,13.3,NaN,NaN,NaN,8.3,NaN,NaN,NaN
4816,NaN,38,NaN,NaN,NaN,17.2,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4817,NaN,279,NaN,NaN,NaN,16.1,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4818,NaN,135,NaN,NaN,NaN,13.9,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4819,NaN,290,NaN,NaN,NaN,14.4,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4820,NaN,150,NaN,NaN,NaN,14.4,NaN,NaN,NaN,12.8,NaN,NaN,NaN
4821,NaN,0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4822,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,8.9,NaN,NaN,NaN
4823,NaN,0,NaN,NaN,NaN,21.1,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4824,NaN,0,NaN,NaN,NaN,23.9,NaN,NaN,NaN,11.7,NaN,NaN,NaN
4825,NaN,0,NaN,NaN,NaN,16.1,NaN,NaN,NaN,11.1,NaN,NaN,NaN
4826,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4827,NaN,25,NaN,NaN,NaN,17.8,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4828,NaN,104,NaN,NaN,NaN,16.1,NaN,NaN,NaN,9.4,NaN,NaN,NaN
4829,NaN,20,NaN,NaN,NaN,15.0,NaN,NaN,NaN,9.4,NaN,NaN,NaN
4830,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4831,NaN,0,NaN,NaN,NaN,17.2,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4832,NaN,0,NaN,NaN,NaN,18.3,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4833,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4834,NaN,0,NaN,NaN,NaN,15.6,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4835,NaN,0,NaN,NaN,NaN,14.4,NaN,NaN,NaN,8.9,NaN,NaN,NaN

In [7]:
df[(df['Quality Flag.4'] != " ")]

,DATE,PRCP,Measurement Flag,Quality Flag,Source Flag,TMAX,Measurement Flag.3,Quality Flag.3,Source Flag.3,TMIN,Measurement Flag.4,Quality Flag.4,Source Flag.4
0,NaN,0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,7.8,NaN,NaN,NaN
1,NaN,0,NaN,NaN,NaN,13.9,NaN,NaN,NaN,8.9,NaN,NaN,NaN
2,NaN,0,NaN,NaN,NaN,17.2,NaN,NaN,NaN,8.3,NaN,NaN,NaN
3,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4,NaN,0,NaN,NaN,NaN,20.6,NaN,NaN,NaN,9.4,NaN,NaN,NaN
5,NaN,0,NaN,NaN,NaN,20.6,NaN,NaN,NaN,11.1,NaN,NaN,NaN
6,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,8.3,NaN,NaN,NaN
7,NaN,0,NaN,NaN,NaN,17.2,NaN,NaN,NaN,7.2,NaN,NaN,NaN
8,NaN,251,NaN,NaN,NaN,13.3,NaN,NaN,NaN,10.0,NaN,NaN,NaN
9,NaN,33,NaN,NaN,NaN,16.1,NaN,NaN,NaN,11.7,NaN,NaN,NaN
10,NaN,0,NaN,NaN,NaN,15.6,NaN,NaN,NaN,11.7,NaN,NaN,NaN
11,NaN,15,NaN,NaN,NaN,16.1,NaN,NaN,NaN,12.2,NaN,NaN,NaN
12,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,12.2,NaN,NaN,NaN
13,NaN,0,NaN,NaN,NaN,16.7,NaN,NaN,NaN,10.6,NaN,NaN,NaN
14,NaN,0,NaN,NaN,NaN,19.4,NaN,NaN,NaN,10.0,NaN,NaN,NaN
15,NaN,0,NaN,NaN,NaN,19.4,NaN,NaN,NaN,9.4,NaN,NaN,NaN
16,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,8.9,NaN,NaN,NaN
17,NaN,0,NaN,NaN,NaN,16.1,NaN,NaN,NaN,7.2,NaN,NaN,NaN
18,NaN,0,NaN,NaN,NaN,11.1,NaN,NaN,NaN,6.7,NaN,NaN,NaN
19,NaN,5,NaN,NaN,NaN,10.6,NaN,NaN,NaN,6.7,NaN,NaN,NaN
20,NaN,86,NaN,NaN,NaN,14.4,NaN,NaN,NaN,9.4,NaN,NaN,NaN
21,NaN,43,NaN,NaN,NaN,16.1,NaN,NaN,NaN,10.6,NaN,NaN,NaN
22,NaN,10,NaN,NaN,NaN,16.1,NaN,NaN,NaN,12.8,NaN,NaN,NaN
23,NaN,0,NaN,NaN,NaN,17.2,NaN,NaN,NaN,12.2,NaN,NaN,NaN
24,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,11.7,NaN,NaN,NaN
25,NaN,0,NaN,NaN,NaN,16.7,NaN,NaN,NaN,12.8,NaN,NaN,NaN
26,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
27,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
28,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,9.4,NaN,NaN,NaN
29,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,10.6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4806,NaN,0,NaN,NaN,NaN,18.3,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4807,NaN,0,NaN,NaN,NaN,21.7,NaN,NaN,NaN,11.1,NaN,NaN,NaN
4808,NaN,0,NaN,NaN,NaN,20.6,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4809,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4810,NaN,20,NaN,NaN,NaN,16.7,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4811,NaN,97,NaN,NaN,NaN,17.2,NaN,NaN,NaN,13.9,NaN,NaN,NaN
4812,NaN,328,NaN,NaN,NaN,17.2,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4813,NaN,114,NaN,NaN,NaN,15.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4814,NaN,135,NaN,NaN,NaN,13.9,NaN,NaN,NaN,8.9,NaN,NaN,NaN
4815,NaN,0,NaN,NaN,NaN,13.3,NaN,NaN,NaN,8.3,NaN,NaN,NaN
4816,NaN,38,NaN,NaN,NaN,17.2,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4817,NaN,279,NaN,NaN,NaN,16.1,NaN,NaN,NaN,13.3,NaN,NaN,NaN
4818,NaN,135,NaN,NaN,NaN,13.9,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4819,NaN,290,NaN,NaN,NaN,14.4,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4820,NaN,150,NaN,NaN,NaN,14.4,NaN,NaN,NaN,12.8,NaN,NaN,NaN
4821,NaN,0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4822,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,8.9,NaN,NaN,NaN
4823,NaN,0,NaN,NaN,NaN,21.1,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4824,NaN,0,NaN,NaN,NaN,23.9,NaN,NaN,NaN,11.7,NaN,NaN,NaN
4825,NaN,0,NaN,NaN,NaN,16.1,NaN,NaN,NaN,11.1,NaN,NaN,NaN
4826,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4827,NaN,25,NaN,NaN,NaN,17.8,NaN,NaN,NaN,12.2,NaN,NaN,NaN
4828,NaN,104,NaN,NaN,NaN,16.1,NaN,NaN,NaN,9.4,NaN,NaN,NaN
4829,NaN,20,NaN,NaN,NaN,15.0,NaN,NaN,NaN,9.4,NaN,NaN,NaN
4830,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,10.0,NaN,NaN,NaN
4831,NaN,0,NaN,NaN,NaN,17.2,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4832,NaN,0,NaN,NaN,NaN,18.3,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4833,NaN,0,NaN,NaN,NaN,18.9,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4834,NaN,0,NaN,NaN,NaN,15.6,NaN,NaN,NaN,10.6,NaN,NaN,NaN
4835,NaN,0,NaN,NaN,NaN,14.4,NaN,NaN,NaN,8.9,NaN,NaN,NaN

In [8]:
df[1955:1965]

,DATE,PRCP,Measurement Flag,Quality Flag,Source Flag,TMAX,Measurement Flag.3,Quality Flag.3,Source Flag.3,TMIN,Measurement Flag.4,Quality Flag.4,Source Flag.4
1955,NaN,0,NaN,NaN,NaN,16.1,NaN,NaN,NaN,8.3,NaN,NaN,NaN
1956,NaN,0,NaN,NaN,NaN,16.7,NaN,NaN,NaN,8.3,NaN,NaN,NaN
1957,NaN,0,NaN,NaN,NaN,15.6,NaN,NaN,NaN,8.9,NaN,NaN,NaN
1958,NaN,0,NaN,NaN,NaN,16.1,NaN,NaN,NaN,10.0,NaN,NaN,NaN
1959,NaN,0,NaN,NaN,NaN,23.9,NaN,NaN,NaN,10.0,NaN,NaN,NaN
1960,NaN,0,NaN,NaN,NaN,27.2,NaN,NaN,NaN,12.2,NaN,NaN,NaN
1961,NaN,0,NaN,NaN,NaN,36.1,NaN,NaN,NaN,20.0,NaN,NaN,NaN
1962,NaN,0,NaN,NaN,NaN,33.3,NaN,NaN,NaN,16.7,NaN,NaN,NaN
1963,NaN,0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,11.1,NaN,NaN,NaN
1964,NaN,0,NaN,NaN,NaN,16.1,NaN,NaN,NaN,10.0,NaN,NaN,NaN

In [9]:
df[2240:2250]

,DATE,PRCP,Measurement Flag,Quality Flag,Source Flag,TMAX,Measurement Flag.3,Quality Flag.3,Source Flag.3,TMIN,Measurement Flag.4,Quality Flag.4,Source Flag.4
2240,NaN,0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,8.3,NaN,NaN,NaN
2241,NaN,0,NaN,NaN,NaN,17.8,NaN,NaN,NaN,7.8,NaN,NaN,NaN
2242,NaN,0,NaN,NaN,NaN,18.3,NaN,NaN,NaN,9.4,NaN,NaN,NaN
2243,NaN,0,NaN,NaN,NaN,10.6,NaN,NaN,NaN,10.0,NaN,NaN,NaN
2244,NaN,315,NaN,NaN,NaN,14.4,NaN,NaN,NaN,11.7,NaN,NaN,NaN
2245,NaN,89,NaN,NaN,NaN,15.0,NaN,NaN,NaN,10.6,NaN,NaN,NaN
2246,NaN,3,NaN,NaN,NaN,11.1,NaN,NaN,NaN,10.6,NaN,NaN,NaN
2247,NaN,53,NaN,NaN,NaN,16.1,NaN,NaN,NaN,10.0,NaN,NaN,NaN
2248,NaN,18,NaN,NaN,NaN,15.0,NaN,NaN,NaN,9.4,NaN,NaN,NaN
2249,NaN,0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,7.8,NaN,NaN,NaN

In [10]:
df[2242:2245]

,DATE,PRCP,Measurement Flag,Quality Flag,Source Flag,TMAX,Measurement Flag.3,Quality Flag.3,Source Flag.3,TMIN,Measurement Flag.4,Quality Flag.4,Source Flag.4
2242,NaN,0,NaN,NaN,NaN,18.3,NaN,NaN,NaN,9.4,NaN,NaN,NaN
2243,NaN,0,NaN,NaN,NaN,10.6,NaN,NaN,NaN,10.0,NaN,NaN,NaN
2244,NaN,315,NaN,NaN,NaN,14.4,NaN,NaN,NaN,11.7,NaN,NaN,NaN

In [11]:
df[(df['DATE'] == 20080125)]

Empty DataFrame
Columns: [DATE, PRCP, Measurement Flag, Quality Flag, Source Flag, TMAX, Measurement Flag.3, Quality Flag.3, Source Flag.3, TMIN, Measurement Flag.4, Quality Flag.4, Source Flag.4]
Index: []

## Actual processing

In [12]:
df = rawdf[['DATE','PRCP','TMAX','TMIN']].copy()
df.loc[2243,'TMAX'] = np.mean([df.TMAX[2242],df.TMAX[2244]])
df.PRCP = df.PRCP.astype(float)/10.
df.TMAX = df.TMAX.astype(float)/10.
df.TMIN = df.TMIN.astype(float)/10.
df[2242:2245]

            DATE  PRCP   TMAX  TMIN
2242  2009-02-20   0.0  18.30   9.4
2243  2009-02-21   0.0  16.35  10.0
2244  2009-02-22  31.5  14.40  11.7

In [13]:
df.dtypes

DATE     object
PRCP    float64
TMAX    float64
TMIN    float64
dtype: object

In [14]:
df.PRCP.describe()

count    4836.000000
mean        1.506824
std         5.459198
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        86.400000
Name: PRCP, dtype: float64

## Read weather, clean, save to pickle

In [15]:
import pandas as pd
import numpy as np
import datetime as dt

path = r"../rawdata/noaa-weather-downtown-sf.csv"

conv = {
        'DATE' : lambda x: dt.datetime.strptime(str(x),"%Y%m%d").date(),
    }

rawdf = pd.read_csv(path,converters = conv)

df = rawdf[['DATE','PRCP','TMAX','TMIN']].copy()
df.loc[2243,'TMAX'] = np.mean([df.TMAX[2242],df.TMAX[2244]])
df.PRCP = df.PRCP.astype(float)/10.
df.TMAX = df.TMAX.astype(float)/10.
df.TMIN = df.TMIN.astype(float)/10.

path = r"../data/noaa-weather-downtown-sf.p"

df.to_pickle(path)